export const FEATURE_LABELS = {
  monthly_income: 'Monthly Income',
  income_stability_score: 'Income Stability',
  employment_tenure_months: 'Employment Tenure',
  monthly_expense_ratio: 'Monthly Expense Ratio',
  savings_rate: 'Savings Rate',
  bank_account_age_months: 'Bank Account Age',
  utility_payment_consistency: 'Utility Payment Consistency',
  rent_payment_consistency: 'Rent Payment Consistency',
  bill_payment_consistency: 'Bill Payment Consistency',
  late_payment_count: 'Late Payment Count',
  average_payment_delay_days: 'Average Payment Delay',
  transaction_count_monthly: 'Monthly Transactions',
  average_transaction_amount: 'Average Transaction Amount',
  recurring_payment_count: 'Recurring Payments',
  subscription_payment_consistency: 'Subscription Consistency',
  balance_stability_score: 'Balance Stability',
  existing_loans: 'Existing Loans',
  loan_repayment_ratio: 'Loan Repayment Ratio',
  debt_to_income_ratio: 'Debt-to-Income Ratio',
  previous_default: 'Previous Default',
  monthly_savings_transactions: 'Monthly Savings Transactions',
  cash_flow_volatility: 'Cash Flow Volatility',
  emergency_fund_months: 'Emergency Fund (months)',
}
